[tool.poetry]
name = "comma"
version = "0.1.0"
description = ""
authors = ["Jérémie Lumbroso <lumbroso@cs.princeton.edu>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = {version = "^2.23.0", optional = true}
chardet = {version = "^3.0.4", optional = true}
binaryornot = {version = "^0.4.4", optional = true}
clevercsv = {version = "^0.6.3", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipykernel = "^5.2.1"

[tool.poetry.extras]
autodetect = ["binaryornot", "clevercsv", "chardet"]
net = ["requests"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
