[tool.poetry]
name = "comma"
version = "0.1.0"
description = ""
authors = ["Jérémie Lumbroso <lumbroso@cs.princeton.edu>"]

[tool.poetry.dependencies]
python = "^3.8"
clevercsv = { version = "^0.5.6", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.extras]
clevercsv = ["clevercsv"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
