
on: ["push", "pull_request"]

name: Comma Continuous Integration

jobs:

  pytest:
    name: Running `pytest`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python & Poetry and install project
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.8.0
          poetry_version: 1.0
          working_directory: "."  # optional, defaults to ".'
          args: install -E 'autodetect net'
      - name: Run pytest
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.8.0
          poetry_version: 1.0
          working_directory: "."
          args: run python -m pytest --cov=comma --cov-branch --cov-fail-under=100 tests/
      - name: Push coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
